<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-06 at 19:32:46.
 */
class FPDFTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var FPDF
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FPDF;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers FPDF::SetMargins
     * @todo   Implement testSetMargins().
     */
    public function testSetMargins()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetLeftMargin
     * @todo   Implement testSetLeftMargin().
     */
    public function testSetLeftMargin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetTopMargin
     * @todo   Implement testSetTopMargin().
     */
    public function testSetTopMargin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetRightMargin
     * @todo   Implement testSetRightMargin().
     */
    public function testSetRightMargin()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetAutoPageBreak
     * @todo   Implement testSetAutoPageBreak().
     */
    public function testSetAutoPageBreak()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetDisplayMode
     * @todo   Implement testSetDisplayMode().
     */
    public function testSetDisplayMode()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetCompression
     * @todo   Implement testSetCompression().
     */
    public function testSetCompression()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetSubject
     * @todo   Implement testSetSubject().
     */
    public function testSetSubject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetAuthor
     * @todo   Implement testSetAuthor().
     */
    public function testSetAuthor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetKeywords
     * @todo   Implement testSetKeywords().
     */
    public function testSetKeywords()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetCreator
     * @todo   Implement testSetCreator().
     */
    public function testSetCreator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::AliasNbPages
     * @todo   Implement testAliasNbPages().
     */
    public function testAliasNbPages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Error
     * @todo   Implement testError().
     */
    public function testError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Open
     * @todo   Implement testOpen().
     */
    public function testOpen()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Close
     * @todo   Implement testClose().
     */
    public function testClose()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::AddPage
     * @todo   Implement testAddPage().
     */
    public function testAddPage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Header
     * @todo   Implement testHeader().
     */
    public function testHeader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Footer
     * @todo   Implement testFooter().
     */
    public function testFooter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::PageNo
     * @todo   Implement testPageNo().
     */
    public function testPageNo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetDrawColor
     * @todo   Implement testSetDrawColor().
     */
    public function testSetDrawColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetFillColor
     * @todo   Implement testSetFillColor().
     */
    public function testSetFillColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetTextColor
     * @todo   Implement testSetTextColor().
     */
    public function testSetTextColor()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::GetStringWidth
     * @todo   Implement testGetStringWidth().
     */
    public function testGetStringWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetLineWidth
     * @todo   Implement testSetLineWidth().
     */
    public function testSetLineWidth()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Line
     * @todo   Implement testLine().
     */
    public function testLine()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Rect
     * @todo   Implement testRect().
     */
    public function testRect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::AddFont
     * @todo   Implement testAddFont().
     */
    public function testAddFont()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetFont
     * @todo   Implement testSetFont().
     */
    public function testSetFont()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetFontSize
     * @todo   Implement testSetFontSize().
     */
    public function testSetFontSize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::AddLink
     * @todo   Implement testAddLink().
     */
    public function testAddLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetLink
     * @todo   Implement testSetLink().
     */
    public function testSetLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Link
     * @todo   Implement testLink().
     */
    public function testLink()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Text
     * @todo   Implement testText().
     */
    public function testText()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::AcceptPageBreak
     * @todo   Implement testAcceptPageBreak().
     */
    public function testAcceptPageBreak()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Cell
     * @todo   Implement testCell().
     */
    public function testCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::MultiCell
     * @todo   Implement testMultiCell().
     */
    public function testMultiCell()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Write
     * @todo   Implement testWrite().
     */
    public function testWrite()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Ln
     * @todo   Implement testLn().
     */
    public function testLn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Image
     * @todo   Implement testImage().
     */
    public function testImage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::GetX
     * @todo   Implement testGetX().
     */
    public function testGetX()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetX
     * @todo   Implement testSetX().
     */
    public function testSetX()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::GetY
     * @todo   Implement testGetY().
     */
    public function testGetY()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetY
     * @todo   Implement testSetY().
     */
    public function testSetY()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::SetXY
     * @todo   Implement testSetXY().
     */
    public function testSetXY()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::Output
     * @todo   Implement testOutput().
     */
    public function testOutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_dochecks
     * @todo   Implement test_dochecks().
     */
    public function test_dochecks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_checkoutput
     * @todo   Implement test_checkoutput().
     */
    public function test_checkoutput()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_getpagesize
     * @todo   Implement test_getpagesize().
     */
    public function test_getpagesize()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_beginpage
     * @todo   Implement test_beginpage().
     */
    public function test_beginpage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_endpage
     * @todo   Implement test_endpage().
     */
    public function test_endpage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_loadfont
     * @todo   Implement test_loadfont().
     */
    public function test_loadfont()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_escape
     * @todo   Implement test_escape().
     */
    public function test_escape()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_textstring
     * @todo   Implement test_textstring().
     */
    public function test_textstring()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_UTF8toUTF16
     * @todo   Implement test_UTF8toUTF16().
     */
    public function test_UTF8toUTF16()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_dounderline
     * @todo   Implement test_dounderline().
     */
    public function test_dounderline()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_parsejpg
     * @todo   Implement test_parsejpg().
     */
    public function test_parsejpg()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_parsepng
     * @todo   Implement test_parsepng().
     */
    public function test_parsepng()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_parsepngstream
     * @todo   Implement test_parsepngstream().
     */
    public function test_parsepngstream()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_readstream
     * @todo   Implement test_readstream().
     */
    public function test_readstream()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_readint
     * @todo   Implement test_readint().
     */
    public function test_readint()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_parsegif
     * @todo   Implement test_parsegif().
     */
    public function test_parsegif()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_newobj
     * @todo   Implement test_newobj().
     */
    public function test_newobj()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putstream
     * @todo   Implement test_putstream().
     */
    public function test_putstream()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_out
     * @todo   Implement test_out().
     */
    public function test_out()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putpages
     * @todo   Implement test_putpages().
     */
    public function test_putpages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putfonts
     * @todo   Implement test_putfonts().
     */
    public function test_putfonts()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putimages
     * @todo   Implement test_putimages().
     */
    public function test_putimages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putimage
     * @todo   Implement test_putimage().
     */
    public function test_putimage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putxobjectdict
     * @todo   Implement test_putxobjectdict().
     */
    public function test_putxobjectdict()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putresourcedict
     * @todo   Implement test_putresourcedict().
     */
    public function test_putresourcedict()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putresources
     * @todo   Implement test_putresources().
     */
    public function test_putresources()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putinfo
     * @todo   Implement test_putinfo().
     */
    public function test_putinfo()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putcatalog
     * @todo   Implement test_putcatalog().
     */
    public function test_putcatalog()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_putheader
     * @todo   Implement test_putheader().
     */
    public function test_putheader()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_puttrailer
     * @todo   Implement test_puttrailer().
     */
    public function test_puttrailer()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers FPDF::_enddoc
     * @todo   Implement test_enddoc().
     */
    public function test_enddoc()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
